### PR TITLE
Improve Camp Workflow

### LINKED ISSUE #25: camp workflow progress bar
- shows current state of camp planning
- skip states 
- show next activities 
- manual state changes

### PR DESCRIPTION
**Pull request by joachimprinzbach**
-

### CODE REVIEW

**Comment by marcosteybe** [comment]
Cool :-)

**Comment by joachimprinzbach** [comment]
closes #28

**Comment by joachimprinzbach** [comment]
Still missing: 

- [ ] Use store for other entities than Hotel

- [ ] Move filter logic to smart components (and extract to  service)

**Comment by joachimprinzbach** [comment]
Added Camp to store.

**Pull request merged**
